/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GroupId = IDL.Nat;
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Username = IDL.Text;
export const UserProfile = IDL.Record({ 'username' : Username });
export const SubmissionId = IDL.Nat;
export const FileStatus = IDL.Variant({
  'pending' : IDL.Null,
  'replied' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileName = IDL.Text;
export const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'image' : IDL.Null });
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'status' : FileStatus,
  'blob' : ExternalBlob,
  'filename' : FileName,
  'filetype' : FileType,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'uploader' : UserId,
  'reply' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemberToGroup' : IDL.Func([GroupId, UserId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Vec(UserId)], [GroupId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroupCreator' : IDL.Func([GroupId], [IDL.Opt(UserId)], ['query']),
  'getGroupMembers' : IDL.Func([GroupId], [IDL.Vec(UserId)], ['query']),
  'getOwnSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isGroupCreator' : IDL.Func([GroupId], [IDL.Bool], ['query']),
  'isGroupMemberQuery' : IDL.Func([GroupId], [IDL.Bool], ['query']),
  'isSubmissionOwnerQuery' : IDL.Func([SubmissionId], [IDL.Bool], ['query']),
  'listAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'removeGroupMember' : IDL.Func([GroupId, UserId], [IDL.Bool], []),
  'replyToSubmission' : IDL.Func([SubmissionId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFile' : IDL.Func(
      [ExternalBlob, FileName, FileType, IDL.Text],
      [SubmissionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GroupId = IDL.Nat;
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Username = IDL.Text;
  const UserProfile = IDL.Record({ 'username' : Username });
  const SubmissionId = IDL.Nat;
  const FileStatus = IDL.Variant({
    'pending' : IDL.Null,
    'replied' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileName = IDL.Text;
  const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'image' : IDL.Null });
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'status' : FileStatus,
    'blob' : ExternalBlob,
    'filename' : FileName,
    'filetype' : FileType,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'uploader' : UserId,
    'reply' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemberToGroup' : IDL.Func([GroupId, UserId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Vec(UserId)], [GroupId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroupCreator' : IDL.Func([GroupId], [IDL.Opt(UserId)], ['query']),
    'getGroupMembers' : IDL.Func([GroupId], [IDL.Vec(UserId)], ['query']),
    'getOwnSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isGroupCreator' : IDL.Func([GroupId], [IDL.Bool], ['query']),
    'isGroupMemberQuery' : IDL.Func([GroupId], [IDL.Bool], ['query']),
    'isSubmissionOwnerQuery' : IDL.Func([SubmissionId], [IDL.Bool], ['query']),
    'listAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'removeGroupMember' : IDL.Func([GroupId, UserId], [IDL.Bool], []),
    'replyToSubmission' : IDL.Func([SubmissionId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFile' : IDL.Func(
        [ExternalBlob, FileName, FileType, IDL.Text],
        [SubmissionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };