/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FileName = string;
export type FileStatus = { 'pending' : null } |
  { 'replied' : null };
export type FileType = { 'pdf' : null } |
  { 'image' : null };
export type GroupId = bigint;
export interface Submission {
  'id' : SubmissionId,
  'status' : FileStatus,
  'blob' : ExternalBlob,
  'filename' : FileName,
  'filetype' : FileType,
  'message' : string,
  'timestamp' : bigint,
  'uploader' : UserId,
  'reply' : [] | [string],
}
export type SubmissionId = bigint;
export type UserId = Principal;
export interface UserProfile { 'username' : Username }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberToGroup' : ActorMethod<[GroupId, UserId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, Array<UserId>], GroupId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroupCreator' : ActorMethod<[GroupId], [] | [UserId]>,
  'getGroupMembers' : ActorMethod<[GroupId], Array<UserId>>,
  'getOwnSubmissions' : ActorMethod<[], Array<Submission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isGroupCreator' : ActorMethod<[GroupId], boolean>,
  'isGroupMemberQuery' : ActorMethod<[GroupId], boolean>,
  'isSubmissionOwnerQuery' : ActorMethod<[SubmissionId], boolean>,
  'listAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'removeGroupMember' : ActorMethod<[GroupId, UserId], boolean>,
  'replyToSubmission' : ActorMethod<[SubmissionId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFile' : ActorMethod<
    [ExternalBlob, FileName, FileType, string],
    SubmissionId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];